spring:
    datasource:
        password: ${DB_USERNAME:postgres}
        url: jdbc:postgresql://${DB_IP:localhost}:${DB_PORT:5432}/pdf_coordinates
        username: ${DB_PASSWORD:postgres}
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                hbm2ddl:
                    "[create_namespaces]": true
management:
    endpoint.health.probes.enabled: true
    health:
        livenessState.enabled: true
        readinessState.enabled: true